# Generated by Django 3.0.6 on 2020-06-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200531_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='frienddetails',
            name='stars',
            field=models.CharField(default='no stars', max_length=255),
        ),
    ]
